extends:
- airbnb
- prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 8
  sourceType: module
env:
  browser: true
  es6: true
rules:
  linebreak-style:
  - error
  - unix
  max-len:
  - error
  - code: 80
  quotes:
  - error
  - double
  semi:
  - error
  - always
  comma-dangle:
  - error
  - always-multiline
  arrow-parens:
  - error
  - always
  object-curly-spacing:
  - error
  - always
  import/extensions:
  - 1
  - always
  prettier/prettier:
  - error
  - trailingComma: es5
    singleQuote: false
    printWidth: 80
    semi: true
    arrowParens: always
plugins:
- prettier
- curry
