extends:
- google
- prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module
env:
  browser: true
  es6: true
rules:
  indent:
  - error
  - 2
  linebreak-style:
  - error
  - unix
  max-len:
  - error
  - code: 80
  quotes:
  - error
  - single
  semi:
  - error
  - always
  prettier/prettier:
  - error
  - trailingComma: es5
    singleQuote: true
    printWidth: 80
    semi: true
plugins:
- prettier
